- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - httpd
    - httpd-tools

- name: Start service httpd, if not started
  service:
    name: httpd
    state: started
    enabled: yes